// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SEKISAN_IRAI.Data;

#nullable disable

namespace SEKISAN_IRAI.Migrations
{
    [DbContext(typeof(EstimateRequestContext))]
    partial class EstimateRequestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SEKISAN_IRAI.Models.EstimateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DesiredEstimateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentsUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EstimateCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estimator")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("ZacProjectNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstimateRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
